module.exports = {
  name: "fortune",

  run: async (client, message) => {

    const fortunes = [
      "🔮 Great luck is coming your way.",
      "🔮 You will achieve something you’ve been working toward.",
      "🔮 A surprise message will brighten your day.",
      "🔮 Patience will reward you soon.",
      "🔮 You will make a valuable connection.",
      "🔮 An exciting opportunity is near.",
      "🔮 Someone appreciates you more than you know.",
      "🔮 A bold move will pay off.",
      "🔮 Happiness begins with gratitude.",
      "🔮 Expect good news within a week.",
      "🔮 A small risk will bring big rewards.",
      "🔮 Trust your instincts today.",
      "🔮 Your hard work is about to shine.",
      "🔮 A fresh start will benefit you.",
      "🔮 You will conquer a challenge soon.",
      "🔮 Joy will find you unexpectedly.",
      "🔮 An old friend may reappear.",
      "🔮 Success is closer than it seems.",
      "🔮 A calm mind brings clear decisions.",
      "🔮 Something lost will be found.",
      "🔮 A dream you have will come true.",
      "🔮 Today is lucky for you.",
      "🔮 You will inspire someone soon.",
      "🔮 Fortune favors your courage.",
      "🔮 A financial gain is possible.",
      "🔮 You will discover hidden talent.",
      "🔮 Peace surrounds your future.",
      "🔮 A compliment is coming your way.",
      "🔮 A new hobby will excite you.",
      "🔮 Your kindness will return tenfold.",
      "🔮 Big changes are ahead.",
      "🔮 A positive attitude changes everything.",
      "🔮 Unexpected luck will surprise you.",
      "🔮 You will overcome doubt.",
      "🔮 A journey may be in your future.",
      "🔮 You will learn something valuable.",
      "🔮 Your confidence will grow.",
      "🔮 Good fortune follows persistence.",
      "🔮 A happy event is approaching.",
      "🔮 You will make someone smile today.",
      "🔮 A challenge will make you stronger.",
      "🔮 Love may be closer than you think.",
      "🔮 You will receive recognition.",
      "🔮 Your future looks bright.",
      "🔮 Luck is on your side.",
      "🔮 You will accomplish a goal soon.",
      "🔮 A new friendship is forming.",
      "🔮 Your creativity will flourish.",
      "🔮 Someone will offer helpful advice.",
      "🔮 A wish you made will manifest.",
      "🔮 Good vibes are coming.",
      "🔮 You will find clarity in confusion.",
      "🔮 A breakthrough is near.",
      "🔮 Your effort will not go unnoticed.",
      "🔮 A secret will be revealed.",
      "🔮 You will gain confidence.",
      "🔮 A lucky encounter awaits.",
      "🔮 Your determination leads to success.",
      "🔮 A peaceful resolution is coming.",
      "🔮 You will feel proud of yourself.",
      "🔮 An exciting challenge awaits.",
      "🔮 You will receive unexpected praise.",
      "🔮 A lucky number will appear soon.",
      "🔮 New beginnings are ahead.",
      "🔮 You will turn a setback into a win.",
      "🔮 A new opportunity will open.",
      "🔮 Your positivity attracts success.",
      "🔮 A small victory will mean a lot.",
      "🔮 You will hear great news.",
      "🔮 A kind gesture will surprise you.",
      "🔮 You are closer to success than you think.",
      "🔮 A wise decision will benefit you.",
      "🔮 You will meet someone inspiring.",
      "🔮 Your patience will pay off.",
      "🔮 An exciting message is coming.",
      "🔮 You will grow stronger this week.",
      "🔮 A good decision is ahead.",
      "🔮 Happiness will find you.",
      "🔮 You will achieve balance.",
      "🔮 A new skill will help you succeed.",
      "🔮 Someone is rooting for you.",
      "🔮 A happy surprise is near.",
      "🔮 Your future self will thank you.",
      "🔮 A creative idea will succeed.",
      "🔮 You will unlock new potential.",
      "🔮 A lucky break is coming.",
      "🔮 Your ambition will guide you.",
      "🔮 A joyful moment awaits.",
      "🔮 You will feel accomplished.",
      "🔮 A meaningful conversation is coming.",
      "🔮 Your strength inspires others.",
      "🔮 A fresh idea will bring success.",
      "🔮 You will solve a problem easily.",
      "🔮 A new chapter begins soon.",
      "🔮 Your dreams are valid.",
      "🔮 You will make progress today.",
      "🔮 An unexpected blessing is near.",
      "🔮 You are destined for success."
    ];

    const randomFortune = fortunes[Math.floor(Math.random() * fortunes.length)];

    await message.channel.send(`**Your Fortune:**\n> ${randomFortune}`);
  }
};
