const jokes = [
    "Why don’t scientists trust atoms? Because they make up everything.",
    "Why did the math book look sad? Because it had too many problems.",
    "Why can’t your nose be 12 inches long? Because then it’d be a foot.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the computer go to the doctor? Because it caught a virus.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you call a fish wearing a crown? A king fish.",
    "Why was the math lecture so long? The professor kept going off on a tangent.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why did the music teacher need a ladder? To reach the high notes.",
    "Why can’t you hear a pterodactyl go to the bathroom? Because the P is silent.",
    "Why did the picture go to jail? Because it was framed.",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the calendar get scared? Its days were numbered.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "Why did the banana go to the doctor? It wasn’t peeling well.",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "Why did the student eat his homework? The teacher said it was a piece of cake.",
    "Why did the broom get promoted? It swept the competition.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the light bulb fail school? It wasn’t too bright.",
    "Why did the pencil get tired? It was pointless.",
    "Why don’t cows have money? Because farmers milk them dry.",
    "Why did the clock go to therapy? It had too many issues with time.",
    "Why did the belt get arrested? It held up a pair of pants.",
    "Why did the computer sit on the floor? It wanted a hard drive.",
    "Why was the math book unhappy? Too many problems.",
    "Why did the grape stop in the middle of the road? It ran out of juice.",
    "Why did the skeleton skip the party? He had no body to go with.",
    "Why was the stadium so cold? It was full of fans.",
    "Why did the duck get detention? For using foul language.",
    "Why did the cow win an award? For outstanding performance in the field.",
    "Why did the notebook break up with the pencil? It felt erased.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why did the math problem look worried? It couldn’t find its solution.",
    "Why don’t elevators tell jokes? They’re afraid of letting people down.",
    "Why did the book go to the gym? To work on its spine.",
    "Why did the robot go on vacation? It needed to recharge.",
    "Why did the bicycle stop moving? It was exhausted.",
    "Why did the student bring a ladder to school? Because they were going to high school.",
    "Why did the snowman call for help? He was having a meltdown.",
    "Why did the computer cross the road? To get to the other site.",
    "Why did the cookie cry? Because its mother was a wafer so long.",
    "Why did the pencil go to jail? For drawing conclusions.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "Why did the golfer bring extra socks? In case he got a hole in one.",
    "Why did the phone wear glasses? Because it lost its contacts.",
    "Why did the orange stop rolling? It ran out of juice.",
    "Why did the kid bring string to school? To tie up loose ends.",
    "Why did the computer take a nap? It needed to rest its memory.",
    "Why did the clock break up with the calendar? Too many dates.",
    "Why did the sheep get a haircut? It was feeling woolly.",
    "Why did the chair break up with the table? Too many arguments.",
    "Why did the math teacher smile? The problem was solved.",
    "Why did the notebook feel important? It had a lot of notes.",
    "Why did the fish blush? It saw the ocean’s bottom.",
    "Why did the eraser feel proud? It fixed mistakes."
];

module.exports = {
    name: ["joke", "jokes"],
    run: async (client, message, args) => {
        const joke = jokes[Math.floor(Math.random() * jokes.length)];
        message.reply(`😂 ${joke}`);
    }
};

