const facts = [
    "Octopuses have three hearts and blue blood.",
    "Bananas are berries, but strawberries aren’t.",
    "A day on Venus is longer than a year on Venus.",
    "Honey never spoils — edible honey has been found in Egyptian tombs.",
    "A single strand of human hair can hold up to 100 grams.",
    "Wombat poop is cube-shaped.",
    "There are more stars in the universe than grains of sand on Earth.",
    "Hot water can freeze faster than cold water under certain conditions (Mpemba effect).",
    "Butterflies taste with their feet.",
    "The Eiffel Tower can be 15 cm taller in summer due to thermal expansion.",
    "Sharks existed before trees evolved.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "A group of flamingos is called a flamboyance.",
    "Humans share about 60% of their DNA with bananas.",
    "Some turtles can breathe through their butts.",
    "Rain contains vitamin B12.",
    "A cloud can weigh more than a million pounds.",
    "Cows have best friends and get stressed when separated.",
    "Sea otters hold hands while sleeping to avoid drifting apart.",
    "Koalas have fingerprints almost identical to humans.",
    "The heart of a blue whale is the size of a small car.",
    "Sloths can hold their breath longer than dolphins.",
    "Jellyfish are 95% water.",
    "A snail can sleep for three years.",
    "An ostrich’s eye is bigger than its brain.",
    "There are more possible games of chess than atoms in the known universe.",
    "Honeybees can recognize human faces.",
    "Some fish can walk on land.",
    "The world’s oldest known living tree is over 4,800 years old.",
    "Ravens can mimic human speech and solve complex problems.",
    "A day on Mercury lasts about 1,408 hours.",
    "Winds on Neptune can reach more than 1,200 miles per hour.",
    "Jupiter’s Great Red Spot is a storm larger than Earth.",
    "The human nose can detect over 1 trillion different scents.",
    "Elephants are one of the few animals that can’t jump.",
    "Penguins propose to their mates with pebbles.",
    "A jiffy is an actual unit of time (~1/100th of a second).",
    "Some mushrooms can glow in the dark.",
    "Tigers have striped skin, not just striped fur.",
    "Your stomach gets a new lining every three days.",
    "The longest-living animal was a clam that lived 507 years.",
    "A human sneeze can travel over 100 miles per hour.",
    "The shortest war in history lasted 38 minutes.",
    "Lobsters taste with their legs and feet.",
    "There are more trees on Earth than stars in the Milky Way.",
    "The tongue is the strongest muscle in proportion to its size.",
    "The sun makes up 99.86% of the mass in our solar system.",
    "A hummingbird’s heart can beat over 1,200 times per minute.",
    "Vultures can soar for hours without flapping their wings.",
    "The fastest land animal is the cheetah, up to 75 mph.",
    "A group of crows is called a murder.",
    "Bees communicate through dance.",
    "Lightning streaks hotter than the surface of the sun.",
    "Starfish can regrow lost arms.",
    "Camels have three sets of eyelids to protect against sandstorms.",
    "The human brain contains roughly 86 billion neurons.",
    "Frogs can freeze without dying.",
    "Polar bear fur is actually transparent, not white.",
    "The Great Barrier Reef is visible from space.",
    "The average person walks the equivalent of three times around Earth in a lifetime.",
    "Penguins can jump up to 6 feet in the air.",
    "Ants never sleep.",
    "Scotland’s national animal is the unicorn.",
    "A day on Saturn lasts just 10.7 hours.",
    "Earth’s magnetic field flips every several hundred thousand years.",
    "Newborns have about 300 bones — adults have 206.",
    "A teaspoon of a neutron star would weigh 6 billion tons.",
    "Some trees can communicate via underground fungal networks.",
    "Glass is actually a liquid over millennia.",
    "The Amazon Rainforest produces 20% of Earth’s oxygen.",
    "Butterflies can see ultraviolet light.",
    "Sharks can detect a drop of blood in 25 gallons of water.",
    "Earth is the only planet not named after a god.",
    "Octopuses use tools like coconuts for protection.",
    "The deepest known point in the ocean is Challenger Deep.",
    "Cats have more bones in their bodies than humans.",
    "The hottest planet in our solar system is Venus, not Mercury.",
    "Some spiders can fly using electric fields."
];


module.exports = {
    name: ["fac", "fact", "facts", "randomfact", "randomfacts", "facs"],

    run: async (client, message, args) => {
        const fact = facts[Math.floor(Math.random() * facts.length)];
        message.reply(`💡 ${fact}`);
    }
};

